# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Terraform
    displayName: "Terraform Init & Plan"
    jobs:
      - job: TerraformJob
        steps:
          - script: |
              echo "== Liste du répertoire cloné ($(System.DefaultWorkingDirectory)) =="
              ls -la "$(System.DefaultWorkingDirectory)"
              echo "== Recherche des fichiers Terraform =="
              find "$(System.DefaultWorkingDirectory)" -maxdepth 1 -name "*.tf" -ls
            displayName: "Lister les fichiers dans le répertoire de travail"

          - script: |
              wget https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
              unzip terraform_1.7.5_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
              terraform -version
            displayName: "Installer Terraform"

          - script: |
              terraform init
              terraform plan -out=tfplan
            displayName: "Terraform Init & Plan"
            workingDirectory: "$(System.DefaultWorkingDirectory)"
