# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

 trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  # Assure-toi que le dépôt est bien cloné
  - checkout: self

  # Étape de débogage : liste récursive de tous les fichiers dans le répertoire cloné
  - script: |
      echo "=== Contenu complet du répertoire de travail ($(System.DefaultWorkingDirectory)) ==="
      ls -laR "$(System.DefaultWorkingDirectory)"
    displayName: "Lister tous les fichiers"

  # Installer Terraform
  - script: |
      wget https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      unzip terraform_1.7.5_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform -version
    displayName: "Installer Terraform"

  # Initialiser Terraform et générer le plan
  - script: |
      terraform init
      terraform plan -out=tfplan
    displayName: "Terraform Init & Plan"
